name: Ruff
on:
  push:
    branches:
      - dev
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-commit ruff style fixes'
